/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PharmacistRouteImport } from './routes/pharmacist'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerOnboardingRouteImport } from './routes/owner.onboarding'

const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacistRoute = PharmacistRouteImport.update({
  id: '/pharmacist',
  path: '/pharmacist',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerOnboardingRoute = OwnerOnboardingRouteImport.update({
  id: '/owner/onboarding',
  path: '/owner/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/pharmacist': typeof PharmacistRoute
  '/search': typeof SearchRoute
  '/transfers': typeof TransfersRoute
  '/owner/onboarding': typeof OwnerOnboardingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/pharmacist': typeof PharmacistRoute
  '/search': typeof SearchRoute
  '/transfers': typeof TransfersRoute
  '/owner/onboarding': typeof OwnerOnboardingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/pharmacist': typeof PharmacistRoute
  '/search': typeof SearchRoute
  '/transfers': typeof TransfersRoute
  '/owner/onboarding': typeof OwnerOnboardingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/billing'
    | '/dashboard'
    | '/pharmacist'
    | '/search'
    | '/transfers'
    | '/owner/onboarding'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/billing'
    | '/dashboard'
    | '/pharmacist'
    | '/search'
    | '/transfers'
    | '/owner/onboarding'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/billing'
    | '/dashboard'
    | '/pharmacist'
    | '/search'
    | '/transfers'
    | '/owner/onboarding'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BillingRoute: typeof BillingRoute
  DashboardRoute: typeof DashboardRoute
  PharmacistRoute: typeof PharmacistRoute
  SearchRoute: typeof SearchRoute
  TransfersRoute: typeof TransfersRoute
  OwnerOnboardingRoute: typeof OwnerOnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacist': {
      id: '/pharmacist'
      path: '/pharmacist'
      fullPath: '/pharmacist'
      preLoaderRoute: typeof PharmacistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/onboarding': {
      id: '/owner/onboarding'
      path: '/owner/onboarding'
      fullPath: '/owner/onboarding'
      preLoaderRoute: typeof OwnerOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BillingRoute: BillingRoute,
  DashboardRoute: DashboardRoute,
  PharmacistRoute: PharmacistRoute,
  SearchRoute: SearchRoute,
  TransfersRoute: TransfersRoute,
  OwnerOnboardingRoute: OwnerOnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
