/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransfersRouteImport } from './routes/transfers'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrescriptionsRouteImport } from './routes/prescriptions'
import { Route as PharmacistRouteImport } from './routes/pharmacist'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PharmacistPrescriptionsRouteImport } from './routes/pharmacist.prescriptions'
import { Route as OwnerOnboardingRouteImport } from './routes/owner.onboarding'
import { Route as BillingSubscriptionRouteImport } from './routes/billing.subscription'
import { Route as BillingPaymentRouteImport } from './routes/billing.payment'
import { Route as BillingInvoicesRouteImport } from './routes/billing.invoices'

const TransfersRoute = TransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionsRoute = PrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacistRoute = PharmacistRouteImport.update({
  id: '/pharmacist',
  path: '/pharmacist',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacistPrescriptionsRoute = PharmacistPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => PharmacistRoute,
} as any)
const OwnerOnboardingRoute = OwnerOnboardingRouteImport.update({
  id: '/owner/onboarding',
  path: '/owner/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingSubscriptionRoute = BillingSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => BillingRoute,
} as any)
const BillingPaymentRoute = BillingPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => BillingRoute,
} as any)
const BillingInvoicesRoute = BillingInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => BillingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/delivery': typeof DeliveryRoute
  '/notifications': typeof NotificationsRoute
  '/pharmacist': typeof PharmacistRouteWithChildren
  '/prescriptions': typeof PrescriptionsRoute
  '/search': typeof SearchRoute
  '/transfers': typeof TransfersRoute
  '/billing/invoices': typeof BillingInvoicesRoute
  '/billing/payment': typeof BillingPaymentRoute
  '/billing/subscription': typeof BillingSubscriptionRoute
  '/owner/onboarding': typeof OwnerOnboardingRoute
  '/pharmacist/prescriptions': typeof PharmacistPrescriptionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/delivery': typeof DeliveryRoute
  '/notifications': typeof NotificationsRoute
  '/pharmacist': typeof PharmacistRouteWithChildren
  '/prescriptions': typeof PrescriptionsRoute
  '/search': typeof SearchRoute
  '/transfers': typeof TransfersRoute
  '/billing/invoices': typeof BillingInvoicesRoute
  '/billing/payment': typeof BillingPaymentRoute
  '/billing/subscription': typeof BillingSubscriptionRoute
  '/owner/onboarding': typeof OwnerOnboardingRoute
  '/pharmacist/prescriptions': typeof PharmacistPrescriptionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/delivery': typeof DeliveryRoute
  '/notifications': typeof NotificationsRoute
  '/pharmacist': typeof PharmacistRouteWithChildren
  '/prescriptions': typeof PrescriptionsRoute
  '/search': typeof SearchRoute
  '/transfers': typeof TransfersRoute
  '/billing/invoices': typeof BillingInvoicesRoute
  '/billing/payment': typeof BillingPaymentRoute
  '/billing/subscription': typeof BillingSubscriptionRoute
  '/owner/onboarding': typeof OwnerOnboardingRoute
  '/pharmacist/prescriptions': typeof PharmacistPrescriptionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/billing'
    | '/dashboard'
    | '/delivery'
    | '/notifications'
    | '/pharmacist'
    | '/prescriptions'
    | '/search'
    | '/transfers'
    | '/billing/invoices'
    | '/billing/payment'
    | '/billing/subscription'
    | '/owner/onboarding'
    | '/pharmacist/prescriptions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/billing'
    | '/dashboard'
    | '/delivery'
    | '/notifications'
    | '/pharmacist'
    | '/prescriptions'
    | '/search'
    | '/transfers'
    | '/billing/invoices'
    | '/billing/payment'
    | '/billing/subscription'
    | '/owner/onboarding'
    | '/pharmacist/prescriptions'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/billing'
    | '/dashboard'
    | '/delivery'
    | '/notifications'
    | '/pharmacist'
    | '/prescriptions'
    | '/search'
    | '/transfers'
    | '/billing/invoices'
    | '/billing/payment'
    | '/billing/subscription'
    | '/owner/onboarding'
    | '/pharmacist/prescriptions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BillingRoute: typeof BillingRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DeliveryRoute: typeof DeliveryRoute
  NotificationsRoute: typeof NotificationsRoute
  PharmacistRoute: typeof PharmacistRouteWithChildren
  PrescriptionsRoute: typeof PrescriptionsRoute
  SearchRoute: typeof SearchRoute
  TransfersRoute: typeof TransfersRoute
  OwnerOnboardingRoute: typeof OwnerOnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transfers': {
      id: '/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof TransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescriptions': {
      id: '/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof PrescriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacist': {
      id: '/pharmacist'
      path: '/pharmacist'
      fullPath: '/pharmacist'
      preLoaderRoute: typeof PharmacistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacist/prescriptions': {
      id: '/pharmacist/prescriptions'
      path: '/prescriptions'
      fullPath: '/pharmacist/prescriptions'
      preLoaderRoute: typeof PharmacistPrescriptionsRouteImport
      parentRoute: typeof PharmacistRoute
    }
    '/owner/onboarding': {
      id: '/owner/onboarding'
      path: '/owner/onboarding'
      fullPath: '/owner/onboarding'
      preLoaderRoute: typeof OwnerOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/subscription': {
      id: '/billing/subscription'
      path: '/subscription'
      fullPath: '/billing/subscription'
      preLoaderRoute: typeof BillingSubscriptionRouteImport
      parentRoute: typeof BillingRoute
    }
    '/billing/payment': {
      id: '/billing/payment'
      path: '/payment'
      fullPath: '/billing/payment'
      preLoaderRoute: typeof BillingPaymentRouteImport
      parentRoute: typeof BillingRoute
    }
    '/billing/invoices': {
      id: '/billing/invoices'
      path: '/invoices'
      fullPath: '/billing/invoices'
      preLoaderRoute: typeof BillingInvoicesRouteImport
      parentRoute: typeof BillingRoute
    }
  }
}

interface BillingRouteChildren {
  BillingInvoicesRoute: typeof BillingInvoicesRoute
  BillingPaymentRoute: typeof BillingPaymentRoute
  BillingSubscriptionRoute: typeof BillingSubscriptionRoute
}

const BillingRouteChildren: BillingRouteChildren = {
  BillingInvoicesRoute: BillingInvoicesRoute,
  BillingPaymentRoute: BillingPaymentRoute,
  BillingSubscriptionRoute: BillingSubscriptionRoute,
}

const BillingRouteWithChildren =
  BillingRoute._addFileChildren(BillingRouteChildren)

interface PharmacistRouteChildren {
  PharmacistPrescriptionsRoute: typeof PharmacistPrescriptionsRoute
}

const PharmacistRouteChildren: PharmacistRouteChildren = {
  PharmacistPrescriptionsRoute: PharmacistPrescriptionsRoute,
}

const PharmacistRouteWithChildren = PharmacistRoute._addFileChildren(
  PharmacistRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BillingRoute: BillingRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DeliveryRoute: DeliveryRoute,
  NotificationsRoute: NotificationsRoute,
  PharmacistRoute: PharmacistRouteWithChildren,
  PrescriptionsRoute: PrescriptionsRoute,
  SearchRoute: SearchRoute,
  TransfersRoute: TransfersRoute,
  OwnerOnboardingRoute: OwnerOnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
